### ISSUE TITLE
Mention the role option in the Documentation

### ISSUE THREAD

**Issue by nnatter** [sulu/SuluCommunityBundle#109]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Community Bundle Version | 26634972fc596da361446c87603de3c366018748

#### Expected Behavior

The `role` parameter should be mentioned in the `Activate Community Features` (https://github.com/sulu/SuluCommunityBundle/blob/develop/Resources/doc/2-setup-webspace.md#activate-community-features) section of the documentation.

**Comment by alexander-schranz** [comment]
The role isn't important for a quick start and is documented in the customization docs: 

https://github.com/sulu/SuluCommunityBundle/blob/3628d78b33c2a20e05840e21b7860ca083bd830d/Resources/doc/3-customization.md#role
