### ISSUE TITLE
Update encoder algorithm to bcrypt

### ISSUE THREAD

**Issue by nnatter** [sulu/SuluCommunityBundle#110]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Community Bundle Version | 26634972fc596da361446c87603de3c366018748

#### Expected Behavior

The encoding algorithm of sulu minimal was changed to bcrypt: https://github.com/sulu/sulu-minimal/commit/92a5f5f91191f3a5966be3a7ad5a21c4bc5d1c7d

Therefore we should update the `Enable Security` (https://github.com/sulu/SuluCommunityBundle/blob/develop/Resources/doc/2-setup-webspace.md#enable-security) section of the documentation.

**Comment by alexander-schranz** [comment]
This was updated.
