### ISSUE TITLE
Notice: Undefined property: Sulu\Bundle\CommunityBundle\Command\InitCommand::$entityManager

### ISSUE THREAD

**Issue by mielcarp** [sulu/SuluCommunityBundle#115]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Community Bundle Version | ^1.1
| Sulu Version | 1.6
| Browser Version | Firefox

#### Actual Behavior

When I run command

php bin/console sulu:community:init

system return:

09:49:52 ERROR     [console] Error thrown while running command "sulu:community:init". Message: "Notice: Undefined property: Sulu\Bundle\CommunityBundle\Command\InitCommand::$entityManager" ["exception" => Symfony\Component\Debug\Excepti
on\ContextErrorException { …},"command" => "sulu:community:init","message" => "Notice: Undefined property: Sulu\Bundle\CommunityBundle\Command\InitCommand::$entityManager"]

In InitCommand.php line 61:

  Notice: Undefined property: Sulu\Bundle\CommunityBundle\Command\InitCommand::$entityManager

#### Possible Solutions

in file:

vendor\sulu\community-bundle\Command\InitCommand.php

in line 64:

$this->entityManager->flush();

replace to:

$entityManager->flush();

**Comment by alexander-schranz** [comment]
Thank you! Fixed in #114 will be released in 1.1.1
