### ISSUE TITLE
Method getUser in AbstractController should not throw an 403 Exception

### ISSUE THREAD

**Issue by HadGS** [sulu/SuluCommunityBundle#123]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Community Bundle Version | develop
| Sulu Version | 2.0.2

#### Actual Behavior

I override some community controllers and need to check if user is logged or not. But controller action getUser throw an 403 Exception if no user is logged.

#### Expected Behavior

Method getUser should not throw an Exception.

#### Possible Solutions

If no user is logged, method getUser should return null and exception should be thrown in calling method.

**Comment by alexander-schranz** [comment]
From security context I'm afraid of changing this behaviour at current state please go with override that method and catch the 403 exception.
