### ISSUE TITLE
Sulu 2.1 Compatibility

### ISSUE THREAD

**Issue by akincer** [sulu/SuluCommunityBundle#128]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Community Bundle Version | develop
| Sulu Version | 2.1RC2

#### Actual Behavior

Cannot install the bundle on Sulu 2.1RC2 due to newer packages and bundles for Sulu 2.1.

#### Expected Behavior

To be able to successfully install community-bundle.

#### Steps to Reproduce

Create a new 2.1RC2 skeleton and attempt to install the community-bundle.

**Comment by alexander-schranz** [comment]
The Symfony 5 / Doctrine Bundle 2 compatibility is merged in #127 so now no downgrading is needed and you shoul be able to install the community bundle without any composer errors.
