### ISSUE TITLE
Missing translations for blacklists

### ISSUE THREAD

**Issue by notsure** [sulu/SuluCommunityBundle#27]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | Specific version or SHA of a commit
| Browser Version | Browser name and version

#### Actual Behavior

Missing translations in Sulu admin "Settings > navigation.settings.blacklist"

#### Expected Behavior

Has default translations.

#### Steps to Reproduce

Include CommunityBundle to Sulu.

#### Possible Solutions

Add default translations.

**Comment by alexander-schranz** [comment]
@notsure the translations exists: https://github.com/sulu/SuluCommunityBundle/blob/develop/Resources/translations/sulu/backend.en.xlf#L5

pls update your translations `app/console sulu:translate:export` t
