### ISSUE TITLE
Password reset on disabled user

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/SuluCommunityBundle#28]
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | no |
#### Actual Behavior

You can reset a password of a user which is not enabled.
#### Expected Behavior

A. User can not disabled because he has not confirm his Mail Address
B. User can reset the password and is automatically enabled because he did confirm the email over the password reset link.

**Comment by alexander-schranz** [comment]
I'm for B. what you think @wachterjohannes

**Comment by wachterjohannes** [comment]
enabled because he has not confirmed his user? or disabled because of an "administrator"? in my opinion the user should not be able to send a password forget email if his user was not confirmed after registration.

**Comment by alexander-schranz** [comment]
@wachterjohannes until it is not possible to resend the confirmation email I would go for B.
