### ISSUE TITLE
Confirmation link language is ignored on redirect

### ISSUE THREAD

**Issue by turbo-ele** [sulu/SuluCommunityBundle#32]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Version | dev-develop#cc64060dd91559a373c216a51ae5668bb25604e6
| Browser Version | chrome

#### Actual Behavior

When calling confirmation link like: 
http://test.com/en/confirmation/bEKXXK_Jjk4YCPSAVYfsrmcxoQgAIgH9WvenwTeR8sg

with redirect link:
/confirmation-completed

i get redirected to sulus default language:

http://test.com/de/confirmation-completed

#### Expected Behavior

I should be redirected to`/en/confirmation-completed`

**Comment by alexander-schranz** [comment]
@turbo-ele pls try if this fit your needs: https://github.com/sulu/SuluCommunityBundle/pull/33

**Comment by turbo-ele** [comment]
@alexander-schranz works like a charm
