### ISSUE TITLE
Can't create a registration/profile form without an address and note

### ISSUE THREAD

**Issue by nickvanderzwet** [sulu/SuluCommunityBundle#45]
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | yes |
| Sulu Version | 7d98fff4a1c8fa0c4892d2367f7a7f5d31c2cd56 |
| Browser Version | Any |
#### Actual Behavior

https://github.com/sulu/SuluCommunityBundle/blob/develop/Controller/ProfileController.php#L137

Sulu adds by default an address and a note. If you don't want this (only a form with the basic profile info such as username) it's _almost_ not possible to skip this step.
#### Expected Behavior

It is possible to don't include an address/note field.
#### Steps to Reproduce

Save the form without the required address/note

![screen shot 2016-10-26 at 13 19 27](https://cloud.githubusercontent.com/assets/13965669/19724121/e1c8e3f6-9b7e-11e6-90ad-d40bb53a72bd.png)
#### Possible Solutions

Make this configurable or perhaps make addAddress / addNote protected instead of private. So it can be overwritten in a client specific class.

**Comment by alexander-schranz** [comment]
If you want no address or note in your form you need todo the following:

```
sulu_community:
    webspaces:
        <your_webspace>:
            profile:
                type: AppBundle\Form\Type\ProfileType
```

There you need to write the following:

```
<?php

namespace AppBundle\Form\Type;

use Sulu\Bundle\CommunityBundle\Form\Type\RegistrationType as SuluRegistrationType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RegistrationType extends SuluRegistrationType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
         parent::buildForm(FormBuilderInterface $builder, array $options);
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
            [
                'contact_type' => RegistrationContactType::class,
                'contact_type_options' => ['label' => false],
            ]
        );
    }
}
```

```
<?php

namespace AppBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;

class RegistrationContactType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('firstName', TextType::class);
        $builder->add('lastName', TextType::class);
    }
}
```

**Comment by alexander-schranz** [comment]
@nickvanderzwet when reading your error message again this seems to be missing in your custom form: https://github.com/sulu/SuluCommunityBundle/blob/1.0.0-RC1/Form/Type/ProfileContactAddressType.php#L28-L31

If this don't help feel free to reopen this issue.
