### ISSUE TITLE
Tests should also be runnned with prefer-lowest

### ISSUE THREAD

**Issue by wachterjohannes** [sulu/SuluCommunityBundle#50]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | `<1.5`
| Browser Version | all

#### Actual Behavior

The tests should run with `--prefer-lowest`. The problem is that sulu `<1.5` is not able to run the tests with lowest.

**Comment by alexander-schranz** [comment]
This is fixed in 2.x (current develop). For 1.x as long as sulu <1.5 is supported this can not be changed.
