### ISSUE TITLE
I can not login with registred user

### ISSUE THREAD

**Issue by ISC3141** [sulu/SuluCommunityBundle#57]
| Bug? | yes?
| Sulu Version | 1.4.7
| Browser Version | Chrome 56.0.2924.87

#### Actual Behavior

I registered a user but then I tried to log on, it just reload the login page without authentification...

#### Expected Behavior

I should be authenticated, right?
(Is it ok that the form login call the same login action. I did not see authentication in this action...)

#### Steps to Reproduce

I just installed and configured the bundle by following the documentation.

#### Possible Solutions

Thank you for your help!

**Comment by reyostallenberg** [comment]
I had this once and then the role settings were not correct.

Are the security settings correct with https://github.com/sulu/SuluCommunityBundle/blob/develop/Resources/doc/2-setup-webspace.md#enable-security-system

Take a look at /admin/#settings/roles and /admin/#settings/roles/edit:{id}/details

**Comment by ISC3141** [comment]
Yes, I followed the security documentation, but when I tried to edit the role, the page did not open correctly because of an error. I will try to reproduce it...

**Comment by ISC3141** [comment]
Any idea?

**Comment by ISC3141** [comment]
I set the sytem of the role to default "Sulu", and I do not have error when editing this role now.
But the login page still doesn't work...
Thanks in advance for your help.

**Comment by alexander-schranz** [comment]
@ISC3141 sorry for the very late reply. if the login page is not visible its mostly a problem with a false configured security.yml. If a user can't login check the `role` of the user. Check that the `role` is in the correct system `se_roles` table. Check if the user is `enabled` and also check that the user is not `locked` in the `se_users` table. if you still have problems let us know.
