### ISSUE TITLE
System added is not shown in the backend role edition

### ISSUE THREAD

**Issue by rflorent** [sulu/SuluCommunityBundle#60]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.5.3

#### Actual Behavior

The system added by the bundle is not shown in the select, when editing a role

#### Expected Behavior

The system should be shown in the select, to avoid loose it when editing a role

#### Steps to Reproduce

Install the bundle, init the bundle and edit a role

![community-role-2](https://cloud.githubusercontent.com/assets/8590540/25272920/ef705e58-2689-11e7-83ab-da3807a7d362.jpg)
![community-role](https://cloud.githubusercontent.com/assets/8590540/25272921/ef90a8c0-2689-11e7-8f6e-570f94bb2a30.jpg)

**Comment by alexander-schranz** [comment]
@danrot @chirimoya systems seems currently be hardcoded.

Solutions:

A. we query the database with `SELECT system FROM se_roles GROUP BY system ORDER BY system` for the select

B. we read the systems from the webspace manager to add them to the select
